# Generated by Django 6.1.1 on 2026-09-30 13:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='название')),
                ('join_code', models.CharField(max_length=8, unique=True, verbose_name='код для учеников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'классы',
                'db_table': 'school_classes',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_answers', models.JSONField(blank=True, default=dict, verbose_name='ответы')),
                ('computed_scores', models.JSONField(blank=True, default=dict, verbose_name='баллы')),
                ('integrity', models.JSONField(blank=True, default=dict, verbose_name='доверие к ответам')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='пройден')),
            ],
            options={
                'verbose_name': 'результат теста',
                'verbose_name_plural': 'результаты тестов',
                'db_table': 'test_results',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_user_id', models.CharField(max_length=128, unique=True, verbose_name='id в мессенджере')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=16, verbose_name='роль')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='имя')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='почта')),
                ('hashed_password', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='класс (номер)')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('school_class', models.CharField(blank=True, db_index=True, max_length=16, null=True, verbose_name='класс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('class_ref', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app.schoolclass', verbose_name='класс (запись)')),
            ],
            options={
                'verbose_name': 'аккаунт сервиса',
                'verbose_name_plural': 'ученики и педагоги',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_response', models.JSONField(blank=True, default=dict, verbose_name='сырой ответ модели')),
                ('professions', models.JSONField(blank=True, default=list, verbose_name='профессии')),
                ('model_used', models.CharField(max_length=128, verbose_name='модель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='app.testresult', verbose_name='результат теста')),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'рекомендации',
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='app.user', verbose_name='ученик')),
                ('xp', models.IntegerField(default=0, verbose_name='опыт')),
                ('streak_days', models.IntegerField(default=0, verbose_name='серия дней')),
                ('best_streak', models.IntegerField(default=0, verbose_name='рекорд серии')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='последняя активность')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'статистика ученика',
                'verbose_name_plural': 'статистика учеников',
                'db_table': 'user_stats',
            },
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='app.user', verbose_name='ученик'),
        ),
        migrations.CreateModel(
            name='TestProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='ответы')),
                ('plan', models.JSONField(blank=True, default=dict, verbose_name='план блока B')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.user', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'черновик теста',
                'verbose_name_plural': 'черновики тестов',
                'db_table': 'test_progress',
            },
        ),
        migrations.CreateModel(
            name='TeacherInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='код')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='для кого')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='выдан')),
                ('expires_at', models.DateTimeField(verbose_name='действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='использован')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.user', verbose_name='выдал')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.user', verbose_name='использовал')),
            ],
            options={
                'verbose_name': 'приглашение педагога',
                'verbose_name_plural': 'приглашения педагогов',
                'db_table': 'teacher_invites',
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=16, verbose_name='задача')),
                ('subject', models.CharField(db_index=True, max_length=32, verbose_name='предмет')),
                ('difficulty', models.CharField(max_length=16, verbose_name='сложность')),
                ('user_answer', models.CharField(max_length=500, verbose_name='ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='верно')),
                ('error_type', models.CharField(max_length=32, verbose_name='тип ошибки')),
                ('confidence', models.FloatField(default=0.0, verbose_name='уверенность')),
                ('answered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='когда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.user', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'попытка решения',
                'verbose_name_plural': 'попытки решения',
                'db_table': 'task_attempts',
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_classes', to='app.user', verbose_name='педагог'),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_version', models.CharField(max_length=32, verbose_name='редакция документа')),
                ('granted_by', models.CharField(default='self', max_length=16, verbose_name='кем дано')),
                ('age_at_consent', models.IntegerField(blank=True, null=True, verbose_name='возраст')),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дано')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='отозвано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.user', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'согласие',
                'verbose_name_plural': 'согласия',
                'db_table': 'consents',
            },
        ),
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='название')),
                ('subjects', models.JSONField(blank=True, default=list, verbose_name='предметы')),
                ('size', models.IntegerField(default=5, verbose_name='задач в паке')),
                ('difficulty', models.CharField(blank=True, max_length=16, null=True, verbose_name='сложность')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='срок')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='выдано')),
                ('school_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.schoolclass', verbose_name='класс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.user', verbose_name='педагог')),
            ],
            options={
                'verbose_name': 'задание классу',
                'verbose_name_plural': 'задания классам',
                'db_table': 'class_assignments',
            },
        ),
        migrations.CreateModel(
            name='BotAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(db_index=True, max_length=16, verbose_name='платформа')),
                ('external_id', models.CharField(db_index=True, max_length=64, verbose_name='id в мессенджере')),
                ('chat_id', models.CharField(max_length=64, verbose_name='чат')),
                ('link_code', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='код привязки')),
                ('current_task_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='текущая задача')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.user', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'собеседник бота',
                'verbose_name_plural': 'собеседники бота',
                'db_table': 'bot_accounts',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, verbose_name='достижение')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='получено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.user', verbose_name='ученик')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
                'db_table': 'user_achievements',
            },
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['user', 'completed_at'], name='ix_test_results_user_completed'),
        ),
        migrations.AddIndex(
            model_name='taskattempt',
            index=models.Index(fields=['user', 'answered_at'], name='ix_task_attempts_user_answered'),
        ),
        migrations.AddConstraint(
            model_name='botaccount',
            constraint=models.UniqueConstraint(fields=('platform', 'external_id'), name='uq_bot_account_platform_user'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='uq_user_achievement'),
        ),
    ]
