# Generated by Django 6.1.1 on 2026-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'ученик'), ('teacher', 'педагог')], default='student', max_length=16, verbose_name='роль'),
        ),
    ]
